export const data = {
  data: [
    {
      id: 3,
      category: "education",
      name: "Maktab Sains PSBS",
      image_url:
        "https://seaseasiahome.files.wordpress.com/2019/08/logo-mspsbs.png",
      class: "Middle - Post-Secondary Education",
      year: "2009 - 2014",
      info: "9 O-level and 3 A-level",
      certificate: "",
      more_info: "9 O-level and 3 A-level",
    },
    {
      id: 4,
      category: "education",
      name: "Universiti Teknologi Brunei",
      image_url: "https://mia23z.netlify.app/img/utb.png",
      course: "Bachelor of Business in Technology Management",
      class: "Undergraduate Degree",
      year: "2015 - 2019",
      info: "Bachelor of Business in Technology Management",
      certificate: "Graduate Second Upper class honours",
      more_info:
        "Graduated Second Upper class honours for Bachelor of Business in Technology Management.",
    },
    {
      id: 5,
      category: "experience",
      name: "Institut Perkhidmatan Awam",
      image_url: "https://mia23z.netlify.app/img/ipa.png",
      position: "Attached Internship",
      year: "January - July 2018 (6 months)",
      info: "Attached internship in the IT department, main task was to develop a database system.",
      more_info:
        "Interned in the IT department of the Civil Service Institute. Over the duration of six months, I was tasked with two assignments and provide technician and logistic services for two events. One of the assignments, Assessment Center Database System are explained further in the projects tab.",
    },
    {
      id: 6,
      category: "experience",
      name: "Starlodge Hotel",
      image_url:
        "https://starlodgebrunei.com/wp-content/uploads/2017/07/LogoStroke.png",
      position: "Driver",
      year: "October 2019 - March 2021 (1.5 year)",
      info: "Worked as room attendant, laundry helper and laundry driver.",
      more_info:
        "Started as part-time room attendant, got transferred as a laundry helper and worked there for three months. On January, I took the opportunity to go full-time as a driver for the laundry department.",
    },
    {
      id: 7,
      category: "projects",
      name: "Tapau.com",
      image_url: "",
      year: "March - April 2017",
      info: "My introduction to web development",
      more_info:
        "Tapau.com is a project that was done for the course Introduction to Web Development when I studied at UTB. Me and my partner develop the website using HTML, CSS, an AJAX template for the cart scriptings and PHP for the backend. My role in the project was the programming development of the website following my partner's design.",
      second_info: "It was never hosted to tapau.com",
      link: "https://tapau23z.netlify.app/index.html",
      framework: true,
      html: true,
      css: true,
    },
    {
      id: 8,
      category: "projects",
      name: "Assessment Center Database System",
      image_url: "",
      year: "March - July 2018",
      info: "Database system based in Microsoft Access developed for Institut Perkhidmatan Awam during internship.",
      more_info:
        "Assessment Center Database System (ACDS) was a project that was assigned to me and a partner during our attached internship at Institut Perkhidmatan Awam. Their assessment center department was using Microsoft Excel as their database system and was long overdue an overhaul of the system. We self-learn and utilized Microsoft Access for the project.",
      second_info:
        "The project was completed but was not deemed usable by the institute.",
    },
    {
      id: 9,
      category: "projects",
      name: "Personal Portfolio",
      image_url: "",
      year: "March 2021",
      info: "First assignment for Coding.bn to practice the usage of Bootstrap.",
      link: "https://mia23z.netlify.app",
      more_info:
        "First assignment for Coding.bn was personal portfolio to practice the usage of bootstrap.",
      framework: true,
      html: true,
      css: true,
      bootstrap: true,
    },
    {
      id: 10,
      category: "projects",
      name: "Tic Tac Toe",
      image_url: "",
      year: "April 2021",
      info: "Coding.bn assignment to practice javascript.",
      link: "https://izzuddinttt.netlify.app",
      git: "https://github.com/izzuddin23ali/tictactoe",
      more_info:
        "Coding.bn's assignment for April was making a game, in order to practice javascript.",
      framework: true,
      html: true,
      css: true,
      bootstrap: true,
      js: true,
    },
    {
      id: 11,
      category: "projects",
      name: "Text Editor",
      image_url: "",
      year: "May 2021",
      info: "Another assignment from Coding.bn to practice javascript.",
      link: "https://texteditor23z.netlify.app/",
      git: "https://github.com/izzuddin23ali/texteditor",
      more_info: "Another assignment from Coding.bn to practice javascript.",
      framework: true,
      html: true,
      css: true,
      bootstrap: true,
      js: true,
    },
    {
      id: 12,
      category: "projects",
      name: "EMBN",
      image_url: "",
      year: "June 2021",
      info: "Third month assignment to test out our full-stack development prowess.",
      link: "https://embn.herokuapp.com/",
      git: "https://github.com/izzuddin23ali/blog",
      more_info:
        "For the third month, Coding.bn assigned the task of developing a full-stack website either individually or within a group. I develop this website with the initial plan of developing a forum for local car enthusiasts as I feel we do not have any focused platform for the car enthusiasts. It then turns into a directory of local businesses that are in the car scene.",
      second_info: "",
      third_info:
        "The forum aforementioned was developed using NodeBB, hosted to emantukaforum.com using Digital Ocean and fully usable. It won't be listed in the projects tab as it was not financially the correct decision to keep it up.",
      framework: true,
      html: true,
      css: true,
      bootstrap: true,
      js: true,
    },
    {
      id: 13,
      category: "projects",
      name: "CatSat",
      image_url: "",
      year: "June 2021",
      info: "Pre-interview test for Synomus, my introduction to React.",
      link: "https://catsat23z.netlify.app",
      git: "https://github.com/izzuddin23ali/catsat",
      more_info:
        "This project was developed for the pre-interview test set by Synomus for their internship position. This was my entry to developing using React.",
      second_info: "",
      framework: true,
      html: true,
      react: true,
      bootstrap: true,
    },
    {
      id: 14,
      category: "training",
      name: "Coding.bn",
      image_url: "https://codingbn.com/creative-startup/img/CBN1.png",
      year: "March - September 2021",
      course: "",
      class: "Vocational Training",
      info: "Full stack developer bootcamp.",
      more_info:
        "Coding.bn is a 6 months course program initiated by AITI Brunei to train unemployed youths with coding/programming skills aligned with demand in the industry.",
    },
    {
      id: 15,
      category: "experience",
      name: "Mumtaz Collections",
      image_url:
        "https://www.mumtazcollections.com/image/catalog/Mumtaz/Logo/mumtaz-logo-150x150.png",
      year: "July - September 2021 (3 months)",
      info: "Internship for Coding.bn. Introduced to OpenCart framework.",
      position: "Intern",
      more_info:
        "Became an intern under the supervision of the general manager of Mumtaz Collections. I learned about how to become a freelancer in the web development industry, how to market, how to conduct business and so on.",
    },
    {
      id: 16,
      category: "projects",
      name: "Instaloader python project",
      image_url: "",
      year: "September 2021",
      git: "https://github.com/izzuddin23ali/instaloader-miniproject",
      info: "First venture into Python, automating Instaloader.",
      more_info:
        "A mini project using Python to read a csv, take a list of IG username, and using the username to download the biography of the profile, overwriting the empty biography cells of the aforementioned csv. The code also downloads the profile picture of the list of IG usernames into one folder.",
      framework: true,
      python: true,
    },
    {
      id: 17,
      category: "projects",
      name: "All About Me",
      year: "September 2021",
      git: "https://github.com/izzuddin23ali/synapse-jsonplaceholder-test",
      link: "https://synapse23z.netlify.app",
      framework: true,
      html: true,
      css: true,
      react: true,
      bootstrap: true,
      info: "Pre-interview test set by Synapse for their web developer trainee position.",
    },
    {
      id: 18,
      category: "featured",
      name: "Serious Women",
      year: "September 2021",
      git: "https://github.com/izzuddin23ali/seriouswomen",
      link: "https://seriouswomen23z.netlify.app/",
      framework: true,
      html: true,
      css: true,
      bootstrap: true,
      info: "Post-interview test set by Hoco for their junior web developer position.",
    },
  ],
};
